merging with Alkalus 5.08
bear989/GT5u-Bears-Den pull request #3
Opened 2018-08-23 20:59 UTC by e99999

merging with Alkalus 5.08

2018-08-23 21:49 UTC, diregarath commented
@e99999 Looks like you were trying to remove the idea files and logs :)  👍

2018-08-24 08:11 UTC, leagris commented
Please remove https://github.com/bear989/GT5u-Bears-Den/pull/3/commits/138985c8667ca7720d27ebcac81cd0bbf47cce1a as this belong to a texture/resource pack as end-user preference.

2018-08-25 00:41 UTC, diregarath requested changes
Please don't merge this until at least gradlew is back, we are building java 1.8 (or do we have a reason to stay with java 7?), and we are using forge 10.13.4.1614-1.7.10.

2018-08-25 00:41 UTC, diregarath commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
Does this need to be committed?  Seems like an IDE file.

2018-08-25 00:41 UTC, diregarath commented on .gitignore
> +*.log
Do we need *.log twice?

2018-08-25 00:41 UTC, diregarath commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
IDE file?

2018-08-25 00:41 UTC, diregarath commented on build.gradle
> -sourceCompatibility = 1.8
Shouldn't we build against java 8?  why not?

2018-08-25 00:41 UTC, diregarath commented on build.properties
> -forge.version=10.13.4.1614-1.7.10
I switched this to 1614 - I would like to keep it on the last version of 1.7.10 forge.

2018-08-25 00:41 UTC, diregarath commented on compile_Gregtech.cmd
> +@echo on
What is this for?  gradlew build is easy enough to run.

2018-08-25 00:41 UTC, diregarath commented on gradlew
> -#!/usr/bin/env bash
Why are we removing gradlew and adding the bat version? I often develop on os x and linux (and cygwin on windows) - this needs to be restored.  We should have both.

2018-08-25 00:41 UTC, diregarath commented on .gitignore
> +*.log
Any reason we are removing the comments that make it easier to understand the gitignore?

2018-08-25 00:41 UTC, diregarath commented on .gitignore
> -### Windows ###
I liked how this was organized so we knew why specific things were being excluded.  We should bring it back if possible.

2018-08-26 15:29 UTC, diregarath approved these changes

2018-08-27 06:20 UTC, merged